# Generated by Django 2.2.1 on 2019-05-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='file',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
